### ISSUE TITLE
ability to support csv

### ISSUE THREAD

**Issue by RedEyedDog** [kendallb/ExcelHelper#1]
Hi, I'm looking to use this class on xlsx and csv, interchangeably. Am i missing something or is this not possible. Can i ask why you haven't included that functionality and built ont op? i know you use OpenXlms but could not you just build on top and check extension with a factory to return the correct implementation?

**Comment by kendallb** [comment]
We use the CsvHelper library that this design was based on for CSV files and the API is similar. I suppose it could be possible to support both through some kind of configuration option. I don’t know if the C1 library we use in production (a lot faster and memory efficient currently than OpenXml) supports rendering to a CSV as opposed to an Excel file.

Anyway long story short I have never considered it but it might be possible.
