### ISSUE TITLE
Incompatible with .NetFramework 4.6

### ISSUE THREAD

**Issue by selecao338** [kendallb/ExcelHelper#2]
Hi Kendall,

I downloaded your Nuget package and installed it to my project but it is not compatible with .Net Framework 4.6. 

Please help to update it.

![image](https://user-images.githubusercontent.com/54369990/63450479-160d4500-c410-11e9-8647-a6c8eaa9ba2e.png)

Thank you so much

**Comment by kendallb** [comment]
The package targets .Net framework 4.6.1 and later, which is why it does not work with 4.6. Is there some reason you cannot use 4.6.1 or later?

I can probably rebuild he NuGet package with the latest dependencies and have it target an earlier version of .Net to make it more compatible.

**Comment by selecao338** [comment]
I change my project to 4.6.1 and I can install it now.

Could you please show me how I can read the Excel file and parse it to a class like CsvReader using your package ?

**Comment by kendallb** [comment]
I tried to back level it and the projects we depend on required 4.6.1, so glad you got it working. I am going to do a new build against the latest version of all the projects shortly.

Lots of example code on how to use it to read into a class like CsvReader can be found in the unit tests for the reader:

https://github.com/kendallb/ExcelHelper/blob/master/src/ExcelHelper.Tests/ExcelReaderTests.cs

But it basically boils down to:

```
    using (var excel = new ExcelReader(stream)) {
        excel.Configuration.RegisterClassMap<PersonMap>();
        var records = excel.GetRecords<Person>().ToList();
        foreach (var record in records) {
            // Do something with each record
        }
    }

```

**Comment by selecao338** [comment]
Thanks for your support
