### ISSUE TITLE
Cells can hold a maximum of 32,767 characters

### ISSUE THREAD

**Issue by yutongliankong** [kendallb/ExcelHelper#7]
Hi 

We used CsvHelper in our system and it's quite awsome as you said. It's quite easy to generate a .csv file very quickly. Now we might need to change to .xlsx format to keep consistent with other existing functions. I found this ExcelHelper is based on CsvHelper and I'm happy to give it a try. But I got error "Cells can hold a maximum of 32,767 characters" during testing. 
I found this was caused by a field value was too long. This field in our system can be 65,535 characters.
I didn't found too many documents about this except using .xlsx which I already used as file extension, and I didn't found a way to set the format in configuration.

I installed ExcelHelper via VS 2019 nuget.

I would appreciate if you can help fixing my issue.

Here is the code I used for testing.

```
using (FileStream writer = new FileStream(filePath, FileMode.OpenOrCreate))
{
    using (ExcelWriter csv = new ExcelWriter(writer))
    {
        csv.WriteRecords(result, true); // where values implements IEnumerable
    }
}
```

Thanks

**Comment by kendallb** [comment]
That is unfortunately a hard limit of the Excel format itself:

https://support.microsoft.com/en-us/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3
